services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: StaffFlow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
       - backup_data:/backups

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=StaffFlow;Username=postgres;Password=123456
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    volumes:
      - backup_data:/backups 

volumes:
  db_data:
  backup_data: 